"""update tree model to store adresses

Revision ID: 518f0443e3de
Revises: 7bfb54e0b198
Create Date: 2025-05-05 10:57:08.992012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518f0443e3de'
down_revision = '7bfb54e0b198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
